server:
  port: 8082

  # 防止乱码
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: lang-chain-4j-2

  data:
    redis:
      host: 192.168.3.19
      port: 6379
      password: "Dev1234!"
      database: 0

langchain4j:
  community:
    redis:
      host: 192.168.3.19
      port: 16379
      password: "Dev1234!"
      user: default
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${ALIYUN-AI-API-KEY}
      model-name: "qwen3-max"
      log-requests: true
      log-responses: true

logging:
  level:
    root: info
    dev.langchain4j: debug